<?php
$url = parse_url($_SERVER['REQUEST_URI']);

// echo '<pre>';
// print_r($url);

$newUrl = function ($page) use ($url) {
                if (! preg_match('/page/', $url['path'])) {
                    return $url['path'] . '/page/' . (int) $page . '?' . $url['query'];
                } else {
                    return preg_replace('@/page/\d+@', '/page/' . (int) $page . '?' . $url['query'], $url['path']);
                }
             };

if ($this->pageCount):
?>
<div class="alert alert-default text-center" role="alert">
    <ul class="pagination pagination-sm">
    <?php if (isset($this->previous)): ?>
    <li><a href="<?php echo $newUrl($this->previous); ?>"><span class="fa fa-chevron-left"></span></a></li>
    <?php else: ?>
    <li class="disabled"><a href="#"><span class="fa fa-chevron-left"></span></a></li>
    <?php endif; ?>

    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <li>
                <a href="<?php echo $newUrl($page); ?>"><?php echo $page; ?></a>
            </li>
        <?php else: ?>
            <li class="active">
                <a href="#"><?php echo $page; ?></a>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php if (isset($this->next)): ?>
    <li><a href="<?php echo $newUrl($this->next); ?>"><span class="fa fa-chevron-right"></span></a></li>
    <?php else: ?>
    <li class="disabled"><a href="#"><span class="fa fa-chevron-right"></span></a></li>
    <?php endif; ?>
   </ul>
</div>
<?php endif; ?>