<div class="row">
    <?php
        $img100 = $this->Ads()->getListMedia(10, 4, null);
        $img100 = $img100[0];
    ?>
    <img src="<?php echo $img100['mediaFile']; ?>" class="img-responsive img100" alt="<?php echo $img100['name']; ?>">
</div>
<div class="row content">
    <div class="col-md-12">
        <div class="row">
            <h1 class="title">
                Erro 404
            </h1>
        </div>
        <div class="row content-text" style="min-height: 500px;">
            <h3>Erro 404: Página não encontrada!</h3>
            <br><br>
            <p><a href="/">Página Inicial</a></p>
        </div>
    </div>
</div>