<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Site\Module'                        => __DIR__ . '/Module.php',
    'Site\Controller\IndexController' => __DIR__ . '/src/Site/Controller/IndexController.php',
    'SiteTest\Framework\TestCase'        => __DIR__ . '/tests/Site/Framework/TestCase.php',
    'SiteTest\SampleTest'                => __DIR__ . '/tests/Site/SampleTest.php',
);
