<?php
$url = $_SERVER['REQUEST_URI'];

$newUrl = function ($page) use ($url) {
                if (!preg_match('/page/', $url))
                    return $url . '/page/' . (int) $page;
                else
                    return preg_replace('@/page/\d@', '/page/' . (int) $page, $url);
             };

if ($this->pageCount):
?>

<div>
    <ul class="pagination">
    <?php if (isset($this->previous)): ?>
        <li><a href="<?php echo $newUrl($this->previous); ?>">«</a></li>
    <?php else: ?>
        <li class="disabled"><a href="#">«</a></li>
    <?php endif; ?>

    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <li>
                <a href="<?php echo $newUrl($page); ?>"><?php echo $page; ?></a>
            </li>
        <?php else: ?>
            <li class="active">
                <a href="#"><?php echo $page; ?></a>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php if (isset($this->next)): ?>
        <li><a href="<?php echo $newUrl($this->next); ?>">»</a></li>
    <?php else: ?>
        <li class="disabled"><a href="#">»</a></li>
    <?php endif; ?>
   </ul>
</div>

<?php endif; ?>