<?php
    echo $this->inlineScript()
                        ->appendFile($this->basePath() . '/vendor/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js')
                        ->appendFile($this->basePath() . '/vendor/bootstrap-datetimepicker/src/js/locales/bootstrap-datetimepicker.pt-BR.js')
                        ->appendFile($this->basePath() . '/js/form/datetime.js')
                        ->appendFile($this->basePath() . '/js/form/navigation.js')
                        ->appendFile($this->basePath() . '/vendor/ckeditor/ckeditor.js');

    $this->inlineScript()->captureStart();
    echo "
    CKEDITOR.replace( 'description', { customConfig: '/js/form/editor.js' } );
    CKEDITOR.replace( 'content', { customConfig: '/js/form/editor.js' } );
    ";
    $this->inlineScript()->captureEnd();

    $routeName = $this->RouteMatch()->getRouteName();
    $controllerName = $this->RouteMatch()->getControllerName();
?>
<div class="row">
    <div class="col-md-10">
        <div class="box">
            <div class="box-body">
                <?php
                $form = $this->form;
                $form->setAttribute('action',$this->url($routeName, array('controller' => $controllerName, 'action' => 'new')));
                $form->prepare();
                ?>
                <?php echo $this->form()->openTag($form); ?>
                <div class="row">
                    <div class="col-md-12">
                    	<div class="form-group">
                    		<h4>Dados principais - <small>Conteúdo do Site</small></h4>
                    	</div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    	<div class="form-group">
                    		<?php echo $this->formRow($form->get('navigationName')); ?>
                    	</div>
                    </div>
                    <div class="col-md-6">
                    	<div class="form-group">
                    		<?php echo $this->formRow($form->get('navigation')); ?>
                    	</div>
                    </div>
                </div>
                <div class="row">
               	    <div class="col-xs-12 col-sm-6 col-md-9">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('title')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-6 col-md-3">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('locale')); ?>
                		</div>
                	</div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                    	<div class="form-group">
                            <h4>Destaque -
                        		<a class="toggle" data-toggle="collapse" data-parent="#accordion" href="#line1">
                                    <span class="glyphicon glyphicon-chevron-down"></span>
                        		</a>
                            </h4>
                    	</div>
                    </div>
                </div>
                <div class="row">
                	<div class="col-xs-12 col-sm-12 col-md-12 panel-collapse collapse" id="line1">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('description')->setLabel('')); ?>
                		</div>
                	</div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                    	<div class="form-group">
                            <h4>Conteúdo</h4>
                    	</div>
                    </div>
                </div>
                <div class="row">
                	<div class="col-xs-12 col-sm-12 col-md-12">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('content')->setLabel('')); ?>
                		</div>
                	</div>
                </div>
                <div class="row">
                	<div class="col-xs-12 col-sm-12 col-md-12">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('url')); ?>
                		</div>
                	</div>
                </div>
                <div class="row">
                	<div class="col-xs-12 col-sm-3 col-md-3">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('entry')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-3 col-md-3">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('output')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-3 col-md-3">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('showDate')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-3 col-md-3">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('showTime')); ?>
                		</div>
                	</div>
                </div>
                <div class="row">
                	<div class="col-xs-12 col-sm-2 col-md-2">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('state')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-2 col-md-2">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('visible')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-2 col-md-2">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('destak')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-2 col-md-2">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('access')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-4 col-md-4">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('revision')); ?>
                		</div>
                	</div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                    	<div class="form-group">
                    		<h4>Informações adicionais</h4>
                    	</div>
                    </div>
                </div>
                <div class="row">
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('createdBy')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('created')); ?>
                		</div>
                	</div>
                </div>
                <div class="row">
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('modifiedBy')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('modified')); ?>
                		</div>
                	</div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                    	<div class="form-group">
                    		<hr>
                    	</div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('security')); ?>
                            <?php echo $this->formRow($form->get('save')->setAttributes(array('class'=>'btn btn-success btn-sm'))); ?>
                            <?php echo $this->formRow($form->get('saveInsert')->setAttributes(array('class'=>'btn btn-success btn-sm'))); ?>
                        </div>
                    </div>
                </div>
                <?php echo $this->form()->closeTag(); ?>
           </div>
        </div>
    </div>
</div>
