<?php
    $routeName = $this->RouteMatch()->getRouteName();
    $controllerName = $this->RouteMatch()->getControllerName();
?>
<div class="row">
    <div class="col-md-10">
        <div class="box">
            <div class="box-body">
                <?php
                $form = $this->form;
                $form->setAttribute('action',$this->url($routeName, array('controller' => $controllerName, 'action' => 'edit')));
                $form->prepare();
                ?>
                <?php echo $this->form()->openTag($form); ?>
                <div class="row">
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('name')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-3 col-md-3">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('parent')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-3 col-md-3">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('isAdmin')); ?>
                		</div>
                	</div>
                </div>
                                <div class="row">
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                            <?php
                            //echo $this->formRow($form->get('navigation'), null, null, 'partials/permission.phtml');
                            echo $this->formRow($form->get('navigation'));
                            ?>
                        </div>
                	</div>
                </div>
                <div class="form-group">
                    <?php //echo $this->formRow($form->get('security')); ?>
                    <?php echo $this->formRow($form->get('id'), null, null, ''); ?>
                	<?php echo $this->formRow($form->get('submit')->setAttributes(array('class'=>'btn btn-success btn-sm'))); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
           </div>
        </div>
    </div>
</div>