<?php
/* @var $container Zend\Navigation\Navigation */
$container = $this->container;
$this->navigation()->setAcl($this->navigation()->menu()->getAcl());
$this->navigation()->setRole($this->navigation()->menu()->getRole());
?>
<ul class="<?php echo $this->navigation()->menu()->getUlClass(); ?>">
    <?php foreach ($container as $page): ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php
        if ( ! $this->navigation()->accept($page)) continue;
        ?>
        <?php $hasChildren = $page->hasPages(true) ?>
        <?php if (!$hasChildren): ?>
            <li<?php if ($page->isActive()) echo ' class="active"' ?>>
                <a
                    class="nav-header"
                    href="<?php echo $page->getHref() ?>"
                    <?php if ($page->getTarget() != ""): ?>
                        target="<?php echo $page->getTarget(); ?>"
                    <?php endif; ?>
                    >
                        <?php if ($page->get("icon") !== ""): ?>
                        <span class="<?php echo $page->get("icon"); ?>"></span>
                    <?php endif; ?>
                    <?php echo $page->getLabel() ?>
                </a>
            </li>
        <?php else: ?>
            <?php
            if ( ! $this->navigation()->accept($page)) continue;
            ?>
            <li class="treeview<?php if ($page->isActive(true)) echo ' active' ?>">
                <a href="<?php echo $page->getHref() ?>"
                    <?php if ($page->getTarget() != ""): ?>
                        target="<?php echo $page->getTarget(); ?>"
                    <?php endif; ?>
                    >
                    <?php if ($page->get("icon") !== ""): ?>
                        <span class="<?php echo $page->get("icon"); ?>"></span>
                    <?php endif; ?>
                    <?php echo $page->getLabel() ?>
                    <b class="fa pull-right fa-angle-down"></b>
                </a>
                <ul class="treeview-menu">
                    <?php foreach ($page->getPages() as $child): ?>
                        <?php if( ! $this->navigation()->accept($child)) continue; ?>
                            <?php if ($child->get("separator") === true): ?>
                                <li class="divider"></li>
                                    <?php
                                    continue;
                                endif;
                                ?>
                            <li<?php if ($child->isActive()) echo ' class="active"' ?>>
                                <a
                                    href="<?php echo $child->getHref() ?>"
                                    <?php if ($child->getTarget() != ""): ?>
                                        target="<?php echo $child->getTarget(); ?>"
                                    <?php endif; ?> >
                                        <?php if ($child->get("icon") !== ""): ?>
                                        <span class="<?php echo $child->get("icon"); ?>"></span>
                                    <?php endif; ?>
                                    <?php echo $child->getLabel() ?>
                                </a>
                            </li>
                        <?php //endif; ?>
                    <?php endforeach ?>
                </ul>
            </li>
            <?php endif ?>
    <?php endforeach ?>
</ul>