<?php
$url = $_SERVER['REQUEST_URI'];
$newUrl = function ($page) use ($url) {
                if (!preg_match('/page/', $url))
                    return $url . '/page/' . (int) $page;
                else
                    return preg_replace('@/page/\d+@', '/page/' . (int) $page, $url);
             };

if ($this->pageCount):
?>
<div>
    <ul class="pagination pagination-sm">
    <?php if (isset($this->previous)): ?>
    <li><a href="<?php echo $newUrl($this->previous); ?>"><span class="fa fa-chevron-left"></span></a></li>
    <?php else: ?>
    <li class="disabled"><a href="#"><span class="fa fa-chevron-left"></span></a></li>
    <?php endif; ?>

    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <li>
                <a href="<?php echo $newUrl($page); ?>"><?php echo $page; ?></a>
            </li>
        <?php else: ?>
            <li class="active">
                <a href="#"><?php echo $page; ?></a>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php if (isset($this->next)): ?>
    <li><a href="<?php echo $newUrl($this->next); ?>"><span class="fa fa-chevron-right"></span></a></li>
    <?php else: ?>
    <li class="disabled"><a href="#"><span class="fa fa-chevron-right"></span></a></li>
    <?php endif; ?>
   </ul>
</div>
<?php endif; ?>