<?php
    $this->inlineScript()->appendFile($this->basePath() . '/js/form/navigation.js');
    $routeName = $this->RouteMatch()->getRouteName();
    $controllerName = $this->RouteMatch()->getControllerName();
?>
<div class="row">
    <div class="col-md-10">
        <div class="box">
            <div class="box-body">
                <?php
                $form = $this->form;
                $form->setAttribute('action',$this->url($routeName, array('controller' => $controllerName, 'action' => 'new')));
                $form->prepare();
                ?>
                <?php echo $this->form()->openTag($form); ?>
                <div class="row">
                    <div class="col-md-12">
                    	<div class="form-group">
                    		<h4>Dados principais - <small>Módulos/Páginas do Sistema</small></h4>
                    	</div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                    	<div class="form-group">
                    		<?php echo $this->formRow($form->get('nameGroup')); ?>
                    	</div>
                    </div>
                </div>
                <div class="row">
               	    <div class="col-xs-12 col-sm-4 col-md-4">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('label')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-4 col-md-4">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('parent')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-4 col-md-4">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('uri')); ?>
                		</div>
                	</div>
                </div>
                <div class="row">
                	<div class="col-xs-12 col-sm-4 col-md-4">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('active')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-4 col-md-4">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('visible')); ?>
                		</div>
                	</div>
                    <div class="col-xs-12 col-sm-4 col-md-4">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('numberOrder')); ?>
                		</div>
                	</div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                    	<div class="form-group">
                    		<h4>Opcional - <small>Deixar em branco</small></h4>
                    	</div>
                    </div>
                </div>
                <div class="row">
                	<div class="col-xs-12 col-sm-3 col-md-3">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('route')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-3 col-md-3">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('resource')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-3 col-md-3">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('controller')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-3 col-md-3">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('nameAction')); ?>
                		</div>
                	</div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                    	<div class="form-group">
                    		<h4>Informações adicionais</h4>
                    	</div>
                    </div>
                </div>
                <div class="row">
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('registeredBy')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('registeredIn')); ?>
                		</div>
                	</div>
                </div>
                <div class="row">
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('modifiedBy')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('modifiedIn')); ?>
                		</div>
                	</div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                    	<div class="form-group">
                    		<hr>
                    	</div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('security')); ?>
                            <?php echo $this->formRow($form->get('save')->setAttributes(array('class'=>'btn btn-success btn-sm'))); ?>
                            <?php echo $this->formRow($form->get('saveInsert')->setAttributes(array('class'=>'btn btn-success btn-sm'))); ?>
                        </div>
                    </div>
                </div>
                <?php echo $this->form()->closeTag(); ?>
           </div>
        </div>
    </div>
</div>
