<?php
    $routeName = $this->RouteMatch()->getRouteName();
    $controllerName = $this->RouteMatch()->getControllerName();
?>
<div class="row">
    <div class="col-md-10">
        <div class="box">
            <div class="box-body">
                <?php
                $form = $this->form;
                $form->setAttribute('action',$this->url($routeName, array('controller' => $controllerName, 'action' => 'new')));
                $form->prepare();
                ?>
                <?php echo $this->form()->openTag($form); ?>
                <div class="row">
                	<div class="col-xs-12 col-sm-8 col-md-8">
                		<div class="form-group">
                	       <?php echo $this->formRow($form->get('name')); ?>
                        </div>
                    </div>
                	<div class="col-xs-12 col-sm-4 col-md-4">
                		<div class="form-group">
                	       <?php echo $this->formRow($form->get('active')); ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('registeredBy')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('registeredIn')); ?>
                		</div>
                	</div>
                </div>
                <div class="row">
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('modifiedBy')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('modifiedIn')); ?>
                		</div>
                	</div>
                </div>
                <div class="row">
                	<div class="form-group"><hr></div>
                </div>
                <div class="form-group">
                    <?php echo $this->formRow($form->get('security')); ?>
                	<?php echo $this->formInput($form->get('send')->setAttributes(array('class'=>'btn btn-success btn-sm'))); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
           </div>
        </div>
    </div>
</div>