<!-- Estatistica -->
<div class="panel panel-default">
    <div class="panel-heading"><strong>Opções de Entrega de Produtos</strong></div>
    <div class="panel-body">
        <dl>
            <dd>
                <form>
                    <div class="form-group">
                        <label for="cep">CEP</label>
                        <input type="text" class="form-control" id="cep" placeholder="CEP">
                    </div>
                    <div class="form-group">
                        <label for="peso">Peso (Kg)</label>
                        <input type="text" class="form-control" id="peso" placeholder="Peso (KG)">
                    </div>
                    <button type="submit" class="btn btn-default">Consultar</button>
                </form>
            </dd>
        </dl>
    </div>
</div>