<?php
    $this->inlineScript()->appendFile($this->basePath() . '/vendor/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js')
                         ->appendFile($this->basePath() . '/vendor/bootstrap-datetimepicker/src/js/locales/bootstrap-datetimepicker.pt-BR.js')
                         ->appendFile($this->basePath() . '/js/form/datetime.js')
                         ->appendFile($this->basePath() . '/vendor/fileinput/js/fileinput.min.js');

    $routeName = $this->RouteMatch()->getRouteName();
    $controllerName = $this->RouteMatch()->getControllerName();
?>
<div class="row">
    <div class="col-md-10">
        <div class="box">
            <div class="box-body">
                <?php
                $form = $this->form;
                $form->setAttribute('action',$this->url($routeName, array('controller' => $controllerName, 'action' => 'edit')));
                $form->prepare();
                ?>
                <?php echo $this->form()->openTag($form); ?>
                <div class="row">
                    <div class="col-md-12">
                    	<div class="form-group">
                    		<h4>Dados da Peça</h4>
                    	</div>
                    </div>
                </div>
                <div class="row">
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                	       <?php echo $this->formRow($form->get('name')); ?>
                        </div>
                    </div>
                	<div class="col-xs-6 col-sm-2 col-md-4">
                		<div class="form-group">
                	       <?php echo $this->formRow($form->get('position')); ?>
                        </div>
                    </div>
                	<div class="col-xs-12 col-sm-2 col-md-1">
                		<div class="form-group">
                	       <?php echo $this->formRow($form->get('orderBy')); ?>
                        </div>
                    </div>
                	<div class="col-xs-12 col-sm-2 col-md-1">
                		<div class="form-group">
                	       <?php echo $this->formRow($form->get('active')); ?>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                	<?php echo $this->formRow($form->get('description')); ?>
                </div>
                <div class="form-group">
                	<?php echo $this->formRow($form->get('mediaFile')); ?>
                </div>
                <div class="form-group">
                	<?php
                	   $image = $form->get('mediaFile')->getValue();
                	   if (file_exists('./public' . $image)){
                	       echo '<img src="' . $image . '" class="img-thumbnail" \>';
                	   }
                	?>
                </div>
                <div class="form-group">
                	<?php echo $this->formRow($form->get('file')->setLabel('Substituir Imagem')); ?>
                </div>
                <div class="form-group">
                	<?php echo $this->formRow($form->get('urlDestination')); ?>
                </div>
                <div class="row">
                    <div class="col-md-12">
                    	<div class="form-group">
                    		<hr>
                    	</div>
                    </div>
                </div>
                <div class="row">
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('registeredBy')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('registeredIn')); ?>
                		</div>
                	</div>
                </div>
                <div class="row">
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('modifiedBy')); ?>
                		</div>
                	</div>
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('modifiedIn')); ?>
                		</div>
                	</div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                    	<div class="form-group">
                    		<hr>
                    	</div>
                    </div>
                </div>
                <div class="form-group">
                    <?php echo $this->formRow($form->get('id')); ?>
                    <?php echo $this->formRow($form->get('security')); ?>
                	<?php echo $this->formInput($form->get('send')->setAttributes(array('class'=>'btn btn-success btn-sm'))); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
           </div>
        </div>
    </div>
</div>