<?php
$this->inlineScript()->appendFile($this->basePath() . '/vendor/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js')
                     ->appendFile($this->basePath() . '/vendor/bootstrap-datetimepicker/src/js/locales/bootstrap-datetimepicker.pt-BR.js')
                     ->appendFile($this->basePath() . '/js/form/datetime.js');

$routeName = $this->RouteMatch()->getRouteName();
$controllerName = $this->RouteMatch()->getControllerName();
?>
<div class="row">
    <div class="col-md-10">
        <div class="box">
            <div class="box-body">
                <?php
                $form = $this->form;
                $form->setAttribute('action',$this->url($routeName, array('controller' => $controllerName, 'action' => 'new')));
                $form->prepare();
                ?>
                <?php echo $this->form()->openTag($form); ?>
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6">
                    	<div class="form-group">
                    		<?php echo $this->formRow($form->get('name')); ?>
                    	</div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6">
                    	<div class="form-group">
                    		<?php echo $this->formRow($form->get('email')); ?>
                    	</div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                    	<div class="form-group">
                    		<?php echo $this->formRow($form->get('role')); ?>
                    	</div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6">
                    	<div class="form-group">
                    		<?php echo $this->formRow($form->get('username')); ?>
                    	</div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6">
                    	<div class="form-group">
                    		<?php echo $this->formRow($form->get('password')); ?>
                    	</div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6">
                    	<div class="form-group">
                    		<?php echo $this->formRow($form->get('active')); ?>
                    	</div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6">
                    	<div class="form-group">
                    		<?php echo $this->formRow($form->get('expireIn')); ?>
                    	</div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('security')); ?>
                            <?php echo $this->formRow($form->get('save')->setAttributes(array('class'=>'btn btn-success btn-sm'))); ?>
                        </div>
                    </div>
                </div>
                <?php echo $this->form()->closeTag(); ?>
           </div>
        </div>
    </div>
</div>