<?php
//echo $this->inlineScript()->appendFile('https://www.google.com/recaptcha/api.js');
$branch = $breadcrumb;
?>
<section class="page-content-header">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <h1>
                    <?php echo $pageName; ?>
                    <?php echo $this->partial('partials/breadcrumb_site.phtml', array('breadcrumb' => $breadcrumb)); ?>
                </h1>
            </div>
        </div>
    </div>
</section>
<div class="container text">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
                <h1 class="title">
                    Entre em Contato
                </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-md-8">
            <?php if ($form != '' ) : ?>
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('contact'));
            $form->prepare();
            ?>
            <?php echo $this->form()->openTag($form); ?>
            <div class="row">
                <div class="col-md-12">
                	<div class="form-group">
                	   <div class="bs-callout bs-callout-success">
                	       <p>Os campos sublinhados são obrigatórios!</p>
                		</div>
                	</div>
                </div>
            </div>
            <div class="form-group">
            	<?php echo $this->formRow($form->get('Nome')); ?>
            </div>
            <div class="form-group">
            	<?php echo $this->formRow($form->get('Assunto')); ?>
            </div>
            <div class="form-group">
            	<?php echo $this->formRow($form->get('Email')); ?>
            </div>
            <div class="form-group">
                <div class="row">
                	<div class="col-xs-12 col-sm-4 col-md-4">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('Telefone')); ?>
                		</div>
                	</div>
                	<div class="col-xs-6 col-sm-4 col-md-4">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('Cidade')); ?>
                		</div>
                	</div>
                	<div class="col-xs-6 col-sm-4 col-md-4">
                		<div class="form-group">
                			<?php echo $this->formRow($form->get('Estado')); ?>
                		</div>
                	</div>
                </div>
            </div>
            <div class="form-group">
                <?php echo $this->formRow($form->get('Mensagem')); ?>
            </div>
            <div class="form-group">
                <?php echo $this->formRow($form->get('security')); ?>
            	<?php echo $this->formRow($form->get('send')); ?>
            </div>
            <?php echo $this->form()->closeTag(); ?>
            <?php else : ?>
            <p><strong>Sua mensagem foi enviada com sucesso!</strong></p>
            <p>Entraremos em contato em breve!</p>
                <br>
                <br>
                <br>
                <br>
            <?php endif; ?>
            <p class="control">
                <a href="javascript:history.back()">
                    <span class="glyphicon glyphicon-chevron-left"></span> voltar
                </a>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <a href="#top">
                    <span class="glyphicon glyphicon-chevron-up"></span> topo da página
                </a>
            </p>
        </div>
        <div>
            <?php if (!empty($content)) : ?>
            <?php echo $content->getContent(); ?>
            <?php endif; ?>
        </div>
    </div>
</div>
